// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/stats/stats.proto

package stats

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PushRequest struct {
	Property             string   `protobuf:"bytes,1,opt,name=property,proto3" json:"property,omitempty"`
	Section              uint32   `protobuf:"varint,2,opt,name=section,proto3" json:"section,omitempty"`
	Id                   uint32   `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushRequest) Reset()         { *m = PushRequest{} }
func (m *PushRequest) String() string { return proto.CompactTextString(m) }
func (*PushRequest) ProtoMessage()    {}
func (*PushRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a7db0dc656c2f16, []int{0}
}

func (m *PushRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushRequest.Unmarshal(m, b)
}
func (m *PushRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushRequest.Marshal(b, m, deterministic)
}
func (m *PushRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushRequest.Merge(m, src)
}
func (m *PushRequest) XXX_Size() int {
	return xxx_messageInfo_PushRequest.Size(m)
}
func (m *PushRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PushRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PushRequest proto.InternalMessageInfo

func (m *PushRequest) GetProperty() string {
	if m != nil {
		return m.Property
	}
	return ""
}

func (m *PushRequest) GetSection() uint32 {
	if m != nil {
		return m.Section
	}
	return 0
}

func (m *PushRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type PushResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushResponse) Reset()         { *m = PushResponse{} }
func (m *PushResponse) String() string { return proto.CompactTextString(m) }
func (*PushResponse) ProtoMessage()    {}
func (*PushResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a7db0dc656c2f16, []int{1}
}

func (m *PushResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushResponse.Unmarshal(m, b)
}
func (m *PushResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushResponse.Marshal(b, m, deterministic)
}
func (m *PushResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushResponse.Merge(m, src)
}
func (m *PushResponse) XXX_Size() int {
	return xxx_messageInfo_PushResponse.Size(m)
}
func (m *PushResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PushResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PushResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*PushRequest)(nil), "stats.PushRequest")
	proto.RegisterType((*PushResponse)(nil), "stats.PushResponse")
}

func init() { proto.RegisterFile("rpc/stats/stats.proto", fileDescriptor_1a7db0dc656c2f16) }

var fileDescriptor_1a7db0dc656c2f16 = []byte{
	// 199 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0xcd, 0x4a, 0x80, 0x40,
	0x10, 0xc7, 0xd1, 0xbe, 0x27, 0xf3, 0xb0, 0x11, 0x2c, 0x9e, 0xc4, 0x93, 0x74, 0x70, 0xa1, 0x1e,
	0x20, 0xe8, 0x09, 0x42, 0x6f, 0xdd, 0x74, 0x9d, 0x74, 0xa9, 0x76, 0xb6, 0xdd, 0x51, 0xe8, 0xed,
	0x43, 0x97, 0xa4, 0x2e, 0x03, 0xbf, 0xff, 0xc0, 0xff, 0x03, 0xee, 0xbc, 0xd3, 0x2a, 0x70, 0xcf,
	0x21, 0xde, 0xc6, 0x79, 0x62, 0x12, 0x67, 0x3b, 0x54, 0x1d, 0x5c, 0xbf, 0x2c, 0x61, 0x6e, 0xf1,
	0x6b, 0xc1, 0xc0, 0xa2, 0x80, 0x4b, 0xe7, 0xc9, 0xa1, 0xe7, 0x6f, 0x99, 0x94, 0x49, 0x7d, 0xd5,
	0x1e, 0x2c, 0x24, 0x5c, 0x04, 0xd4, 0x6c, 0xc8, 0xca, 0xb4, 0x4c, 0xea, 0x9b, 0xf6, 0x17, 0x45,
	0x0e, 0xa9, 0x19, 0xe5, 0xc9, 0x2e, 0xa6, 0x66, 0xac, 0x72, 0xc8, 0xa2, 0x69, 0x70, 0x64, 0x03,
	0x3e, 0x3c, 0x41, 0xd6, 0x6d, 0x69, 0x1d, 0xfa, 0xd5, 0x68, 0x14, 0x0a, 0x4e, 0xb7, 0xbf, 0x10,
	0x4d, 0x6c, 0xf4, 0xa7, 0x41, 0x71, 0xfb, 0x4f, 0x8b, 0x06, 0xcf, 0xf7, 0xaf, 0xf5, 0x64, 0x78,
	0x5e, 0x86, 0x46, 0xd3, 0xa7, 0x7a, 0xa3, 0x8f, 0x77, 0xb4, 0x93, 0xb1, 0xa8, 0x26, 0xea, 0xc7,
	0x15, 0x2d, 0xab, 0x63, 0xe4, 0x70, 0xbe, 0xef, 0x7b, 0xfc, 0x09, 0x00, 0x00, 0xff, 0xff, 0xc3,
	0x40, 0xcc, 0x37, 0xf8, 0x00, 0x00, 0x00,
}
